### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/data-feed-reader-example#31]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Repo setup requirements as per [new_repo_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_repo_creation_checklist.md):
- [x] Add repo link to some relevant page if applicable (e.g. api3 docs, npm package link, ...)
- [ ] Add the relevant license file (LICENSE) consistent with the organizational standards or project requirements.

**Comment by acenolaza** [comment]
Docs being updated [here](https://github.com/api3dao/data-feed-reader-example/pull/61)
